{% set version = "3.2.7" %}

package:
  name: paste
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/Paste/Paste-{{ version }}.tar.gz
  sha256: 21168702f8fcdea7846bce36c549808346acc2c025324bcb127a9dbfe8a97a66

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - setuptools
    - six >=1.4.0

test:
  imports:
    - paste
    - paste.auth
    - paste.cowbell
    - paste.debug
    - paste.evalexception
    - paste.exceptions
    - paste.util
  requires:
    - nose >=0.11

about:
  home: http://pythonpaste.org
  license: MIT
  license_file: license.txt
  summary: 'Tools for using a Web Server Gateway Interface stack'

extra:
  recipe-maintainers:
    - kwilcox
    - daf
