{% set version = "3.4.2" %}

package:
  name: paste
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/Paste/Paste-{{ version }}.tar.gz
  sha256: c44055ebbbdd4da358cb1abe3552805fddc9b7bf15b02d35cf942487179c8511

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - six >=1.4.0

test:
  imports:
    - paste
    - paste.auth
    - paste.cowbell
    - paste.debug
    - paste.evalexception
    - paste.exceptions
    - paste.util
  requires:
    - nose >=0.11

about:
  home: http://pythonpaste.org
  license: MIT
  license_file: license.txt
  summary: Tools for using a Web Server Gateway Interface stack

extra:
  recipe-maintainers:
    - kwilcox
    - daf
