{% set version = "3.4.0" %}

package:
  name: paste
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/Paste/Paste-{{ version }}.tar.gz
  sha256: 0330d22d1a5cc7202109151322d681f06e14552d43cb99957a21320f3764519b

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - six >=1.4.0

test:
  imports:
    - paste
    - paste.auth
    - paste.cowbell
    - paste.debug
    - paste.evalexception
    - paste.exceptions
    - paste.util
  requires:
    - nose >=0.11

about:
  home: http://pythonpaste.org
  license: MIT
  license_file: license.txt
  summary: 'Tools for using a Web Server Gateway Interface stack'

extra:
  recipe-maintainers:
    - kwilcox
    - daf
